export const K8S_ABBR: Record<string, string> = {
  'cluster-role-bindings': 'crb',
  'cluster-roles': 'cr',
  'config-maps': 'cm',
  'cron-jobs': 'cjb',
  'daemon-sets': 'ds',
  deployments: 'deploy',
  endpoints: 'ep',
  ingress: 'ing',
  jobs: 'jb',
  namespaces: 'ns',
  'network-policies': 'np',
  nodes: 'no',
  'persistent-volume-claims': 'pvc',
  'persistent-volumes': 'pv',
  pods: 'po',
  'replica-sets': 'rs',
  'replication-controllers': 'rc',
  'role-bindings': 'rob',
  'roles': 'ro',
  secrets: 'scr',
  'service-accounts': 'sa',
  services: 'svc',
  'stateful-sets': 'ss',
  'storage-classes': 'sc'
};